web:
  server:
    port: 20011
    debug: true
  cache:
    path: tmp/cache
  log:
    path: tmp/log.log
    level: info
db:
  type: mysql
  url: mysql://localhost:3306/test
  user: root
  password: 123456


